/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HamsterService } from "../hamster.service";
import { HamsterCreateInput } from "./HamsterCreateInput";
import { Hamster } from "./Hamster";
import { HamsterFindManyArgs } from "./HamsterFindManyArgs";
import { HamsterWhereUniqueInput } from "./HamsterWhereUniqueInput";
import { HamsterUpdateInput } from "./HamsterUpdateInput";
import { BetFindManyArgs } from "../../bet/base/BetFindManyArgs";
import { Bet } from "../../bet/base/Bet";
import { BetWhereUniqueInput } from "../../bet/base/BetWhereUniqueInput";

export class HamsterControllerBase {
  constructor(protected readonly service: HamsterService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Hamster })
  async createHamster(
    @common.Body() data: HamsterCreateInput
  ): Promise<Hamster> {
    return await this.service.createHamster({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        strength: true,
        speed: true,
        health: true,
        owner: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Hamster] })
  @ApiNestedQuery(HamsterFindManyArgs)
  async hamsters(@common.Req() request: Request): Promise<Hamster[]> {
    const args = plainToClass(HamsterFindManyArgs, request.query);
    return this.service.hamsters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        strength: true,
        speed: true,
        health: true,
        owner: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Hamster })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async hamster(
    @common.Param() params: HamsterWhereUniqueInput
  ): Promise<Hamster | null> {
    const result = await this.service.hamster({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        strength: true,
        speed: true,
        health: true,
        owner: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Hamster })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHamster(
    @common.Param() params: HamsterWhereUniqueInput,
    @common.Body() data: HamsterUpdateInput
  ): Promise<Hamster | null> {
    try {
      return await this.service.updateHamster({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          strength: true,
          speed: true,
          health: true,
          owner: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Hamster })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHamster(
    @common.Param() params: HamsterWhereUniqueInput
  ): Promise<Hamster | null> {
    try {
      return await this.service.deleteHamster({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          strength: true,
          speed: true,
          health: true,
          owner: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bets")
  @ApiNestedQuery(BetFindManyArgs)
  async findBets(
    @common.Req() request: Request,
    @common.Param() params: HamsterWhereUniqueInput
  ): Promise<Bet[]> {
    const query = plainToClass(BetFindManyArgs, request.query);
    const results = await this.service.findBets(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,

        user: {
          select: {
            id: true,
          },
        },

        match: {
          select: {
            id: true,
          },
        },

        hamster: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bets")
  async connectBets(
    @common.Param() params: HamsterWhereUniqueInput,
    @common.Body() body: BetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bets: {
        connect: body,
      },
    };
    await this.service.updateHamster({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bets")
  async updateBets(
    @common.Param() params: HamsterWhereUniqueInput,
    @common.Body() body: BetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bets: {
        set: body,
      },
    };
    await this.service.updateHamster({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bets")
  async disconnectBets(
    @common.Param() params: HamsterWhereUniqueInput,
    @common.Body() body: BetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bets: {
        disconnect: body,
      },
    };
    await this.service.updateHamster({
      where: params,
      data,
      select: { id: true },
    });
  }
}
