/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Bet as PrismaBet,
  User as PrismaUser,
  Match as PrismaMatch,
  Hamster as PrismaHamster,
} from "@prisma/client";

export class BetServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.BetCountArgs, "select">): Promise<number> {
    return this.prisma.bet.count(args);
  }

  async bets(args: Prisma.BetFindManyArgs): Promise<PrismaBet[]> {
    return this.prisma.bet.findMany(args);
  }
  async bet(args: Prisma.BetFindUniqueArgs): Promise<PrismaBet | null> {
    return this.prisma.bet.findUnique(args);
  }
  async createBet(args: Prisma.BetCreateArgs): Promise<PrismaBet> {
    return this.prisma.bet.create(args);
  }
  async updateBet(args: Prisma.BetUpdateArgs): Promise<PrismaBet> {
    return this.prisma.bet.update(args);
  }
  async deleteBet(args: Prisma.BetDeleteArgs): Promise<PrismaBet> {
    return this.prisma.bet.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.bet
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }

  async getMatch(parentId: string): Promise<PrismaMatch | null> {
    return this.prisma.bet
      .findUnique({
        where: { id: parentId },
      })
      .match();
  }

  async getHamster(parentId: string): Promise<PrismaHamster | null> {
    return this.prisma.bet
      .findUnique({
        where: { id: parentId },
      })
      .hamster();
  }
}
